[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "com.vineat.team.vineat_app://login-callback",
  "com.vineat.team.vineat_app.preview://login-callback",
]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false
otp_length = 6
otp_expiry = 3600

[functions.household]
verify_jwt = true
